server:
  port: 9001


spring:
  application:
    name: contact-service


eureka:
  client:
    register-with-eureka: false 
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.43.2/eureka  #If the client not registering then change the ip address.