server:
  port: 9001


spring:
  application:
    name: contact-service


eureka:
  client:
    register-with-eureka: true 
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.5.191:8761  #If the client not registering then change the ip address.